import { cn } from "@/lib/utils";
import { reportStickySheetHeaderClass } from "@/pages/accounting/reports/components/report-sticky";
import { formatBsDate } from "@/pages/accounting/reports/components/BalanceSheetStatement";

const FINVOROO_LOGO = "/media/app/finvoroo.svg";

function CompanyLogo({ logoUrl, companyName, compact = false }) {
  if (logoUrl) {
    return (
      <img
        src={logoUrl}
        alt=""
        className={cn(
          'w-auto shrink-0 object-contain',
          compact
            ? 'h-8 max-w-[96px] print:h-7 print:max-w-[80px]'
            : 'mb-3 h-12 max-w-[160px] print:mb-1 print:h-8 print:max-w-[120px]',
        )}
      />
    );
  }

  const words = String(companyName || '')
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  const initials =
    words.length >= 2
      ? `${words[0][0] ?? ''}${words[1][0] ?? ''}`.toUpperCase()
      : (words[0] ?? 'C').slice(0, 2).toUpperCase();

  return (
    <div
      aria-hidden
      className={cn(
        'flex shrink-0 items-center justify-center border border-slate-300 text-xs font-semibold tracking-wide text-slate-600',
        compact ? 'size-8' : 'mb-3 size-10',
      )}
    >
      {initials}
    </div>
  );
}

export function PharmacyReportHeader({
  companyName,
  logoUrl,
  title,
  subtitle,
  currency,
  fiscalYear,
  generatedBy,
  printedAt,
  compact = false,
}) {
  const metaParts = [
    currency ? `${currency}` : null,
    fiscalYear ? fiscalYear : null,
    generatedBy ? `By ${generatedBy}` : null,
    printedAt || null,
  ].filter(Boolean);

  if (compact) {
    return (
      <header
        className={cn(
          'balance-sheet-header border-b border-slate-200 px-5 py-3 print:px-4 print:py-2 sm:px-6',
          reportStickySheetHeaderClass,
        )}
      >
        <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex min-w-0 items-center gap-3">
            <CompanyLogo logoUrl={logoUrl} companyName={companyName} compact />
            <div className="min-w-0">
              <p className="truncate text-sm font-semibold leading-tight text-slate-900">
                {companyName || 'Company'}
              </p>
              {subtitle ? (
                <p className="mt-0.5 truncate text-xs text-slate-500">{subtitle}</p>
              ) : title ? (
                <p className="mt-0.5 truncate text-xs font-medium uppercase tracking-wide text-slate-500">
                  {title}
                </p>
              ) : null}
            </div>
          </div>
          {metaParts.length ? (
            <p className="shrink-0 text-[11px] leading-snug text-slate-400 sm:text-right">
              {metaParts.join(' · ')}
            </p>
          ) : null}
        </div>
      </header>
    );
  }

  return (
    <header
      className={cn(
        'balance-sheet-header border-b border-slate-200 px-6 py-6 print:py-3 sm:px-8 print:px-4',
        reportStickySheetHeaderClass,
      )}
    >
      <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
        <div className="min-w-0 flex-1 text-center sm:text-left">
          <div className="flex flex-col items-center sm:items-start">
            <CompanyLogo logoUrl={logoUrl} companyName={companyName} />
          </div>
          <h1 className="text-lg font-semibold leading-tight tracking-tight text-slate-900 sm:text-xl">
            {companyName || 'Company'}
          </h1>
          {title ? (
            <p className="mt-2 text-xs font-semibold uppercase tracking-[0.12em] text-slate-600">
              {title}
            </p>
          ) : null}
          {subtitle ? (
            <p className="mt-1.5 text-sm text-slate-800">{subtitle}</p>
          ) : null}
        </div>
        <div className="shrink-0 text-center text-xs leading-relaxed text-slate-500 sm:text-right">
          {currency ? (
            <p className="font-semibold uppercase tracking-wide text-slate-600">
              Currency: {currency}
            </p>
          ) : null}
          {fiscalYear ? <p className="mt-1">Fiscal year: {fiscalYear}</p> : null}
          {generatedBy ? <p className="mt-1">Generated by {generatedBy}</p> : null}
          {printedAt ? <p className="mt-1">{printedAt}</p> : null}
        </div>
      </div>
    </header>
  );
}

export function PharmacyReportFooter({ note }) {
  return (
    <footer className="balance-sheet-footer border-t border-slate-200 px-6 py-4 print:px-4 print:py-2 sm:px-8">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <p className="max-w-xl text-xs leading-relaxed text-slate-500">
          {note}
        </p>
        <div className="flex items-center justify-between gap-6 sm:justify-end">
          <img
            src={FINVOROO_LOGO}
            alt="Finvoroo"
            className="h-5 w-auto opacity-70 print:h-4"
          />
          <p className="text-xs text-slate-500">
            Unaudited — For management purposes only
          </p>
        </div>
      </div>
    </footer>
  );
}

export function formatReportMoney(value) {
  const n = Number(value);
  if (!Number.isFinite(n)) return "0.00";
  const formatted = new Intl.NumberFormat("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(Math.abs(n));
  return n < 0 ? `(${formatted})` : formatted;
}

export function formatReportDate(value) {
  return formatBsDate(value);
}

export function resolveFiscalYear(asOfDate, company) {
  if (company?.fiscal_year) return company.fiscal_year;
  if (company?.fiscal_year_label) return company.fiscal_year_label;
  if (!asOfDate) return null;
  try {
    return `FY ${String(asOfDate).slice(0, 4)}`;
  } catch {
    return null;
  }
}
