import { cn } from "@/lib/utils";
import { formatBsDate } from "./BalanceSheetStatement";
import { reportStickySheetHeaderClass } from "./report-sticky";
import { LedgerStatementPrintFooter } from "./GeneralLedgerStatement";
import { AccountStatementTable } from "./AccountStatementTable";

const FINVOROO_LOGO = "/media/app/finvoroo.svg";

function CompanyLogo({ logoUrl, companyName }) {
  if (logoUrl) {
    return (
      <img
        src={logoUrl}
        alt=""
        className="mb-3 h-12 w-auto max-w-[160px] object-contain print:mb-1 print:h-8 print:max-w-[120px]"
      />
    );
  }

  const words = String(companyName || "")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  const initials =
    words.length >= 2
      ? `${words[0][0] ?? ""}${words[1][0] ?? ""}`.toUpperCase()
      : (words[0] ?? "C").slice(0, 2).toUpperCase();

  return (
    <div
      aria-hidden
      className="mb-3 flex size-10 items-center justify-center border border-slate-300 text-xs font-semibold tracking-wide text-slate-600"
    >
      {initials}
    </div>
  );
}

function AccountStatementHeader({
  companyName,
  logoUrl,
  periodFrom,
  periodTo,
  currency,
  fiscalYear,
  generatedBy,
  printedAt,
  accountLabel,
  lineCount,
}) {
  const periodLine =
    periodFrom && periodTo
      ? `${formatBsDate(periodFrom)} – ${formatBsDate(periodTo)}`
      : null;
  const activityLabel = `${lineCount} ${
    lineCount === 1 ? "transaction" : "transactions"
  } in period`;

  return (
    <header
      className={cn(
        "balance-sheet-header account-statement-header border-b border-slate-200 px-6 py-6 print:py-3 sm:px-8 print:px-4",
        reportStickySheetHeaderClass,
      )}
    >
      <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
        <div className="min-w-0 flex-1 text-center sm:text-left">
          <div className="flex flex-col items-center sm:items-start">
            <CompanyLogo logoUrl={logoUrl} companyName={companyName} />
          </div>
          <h1 className="text-lg font-semibold leading-tight tracking-tight text-slate-900 sm:text-xl">
            {companyName || "Company"}
          </h1>
          <p className="mt-2 text-xs font-semibold uppercase tracking-[0.12em] text-slate-600">
            Account Statement
          </p>
          {periodLine ? (
            <p className="mt-1.5 text-sm text-slate-800">{periodLine}</p>
          ) : null}
          {accountLabel ? (
            <p className="mt-1 text-xs text-slate-500">Account: {accountLabel}</p>
          ) : null}
        </div>

        <div className="shrink-0 text-center text-xs leading-relaxed text-slate-500 sm:text-right">
          <p className="font-semibold uppercase tracking-wide text-slate-600">
            Currency: {currency}
          </p>
          {fiscalYear ? <p className="mt-1">Fiscal year: {fiscalYear}</p> : null}
          <p className="mt-1">{activityLabel}</p>
          {generatedBy ? (
            <p className="mt-1">Generated by {generatedBy}</p>
          ) : null}
          {printedAt ? <p className="mt-1">{printedAt}</p> : null}
        </div>
      </div>
    </header>
  );
}

export function AccountStatementStatement({
  companyName,
  logoUrl,
  periodFrom,
  periodTo,
  currency,
  fiscalYear,
  generatedBy,
  printedAt,
  account,
  rows,
  loading,
  workspaceId,
  period,
  visibleColumns,
  openingBalance,
  closingBalance,
  totalDebit,
  totalCredit,
  lineCount,
  columnWidths,
  onColumnResize,
  reportKey = "account_statement",
}) {
  const accountLabel = account
    ? `${account.code} — ${account.name}`
    : "Account";

  return (
    <div className="general-ledger-statement account-statement-statement bg-white font-sans">
      <AccountStatementHeader
        companyName={companyName}
        logoUrl={logoUrl}
        periodFrom={periodFrom}
        periodTo={periodTo}
        currency={currency}
        fiscalYear={fiscalYear}
        generatedBy={generatedBy}
        printedAt={printedAt}
        accountLabel={accountLabel}
        lineCount={lineCount}
      />

      <AccountStatementTable
        account={account}
        rows={rows}
        loading={loading}
        workspaceId={workspaceId}
        period={period}
        currency={currency}
        openingBalance={openingBalance}
        closingBalance={closingBalance}
        totalDebit={totalDebit}
        totalCredit={totalCredit}
        visibleColumns={visibleColumns}
        columnWidths={columnWidths}
        onColumnResize={onColumnResize}
        reportKey={reportKey}
      />

      <LedgerStatementPrintFooter />
    </div>
  );
}
