import { Landmark, TrendingDown, TrendingUp, Wallet } from "lucide-react";
import { cn } from "@/lib/utils";
import { reportStickySheetHeaderClass } from "./report-sticky";
import { formatBsAmount, formatBsDate } from "./BalanceSheetStatement";

const FINVOROO_LOGO = "/media/app/finvoroo.svg";

function CompanyLogo({ logoUrl, companyName }) {
  if (logoUrl) {
    return (
      <img
        src={logoUrl}
        alt=""
        className="mb-3 h-12 w-auto max-w-[160px] object-contain print:mb-1 print:h-8 print:max-w-[120px]"
      />
    );
  }

  const words = String(companyName || "")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  const initials =
    words.length >= 2
      ? `${words[0][0] ?? ""}${words[1][0] ?? ""}`.toUpperCase()
      : (words[0] ?? "C").slice(0, 2).toUpperCase();

  return (
    <div
      aria-hidden
      className="mb-3 flex size-10 items-center justify-center border border-slate-300 text-xs font-semibold tracking-wide text-slate-600"
    >
      {initials}
    </div>
  );
}

function StatementHeader({
  companyName,
  logoUrl,
  periodFrom,
  periodTo,
  currency,
  fiscalYear,
  generatedBy,
  printedAt,
}) {
  return (
    <header className={cn(
      "balance-sheet-header border-b border-slate-200 px-6 py-6 print:py-3 sm:px-8 print:px-4",
      reportStickySheetHeaderClass,
    )}>
      <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
        <div className="min-w-0 flex-1 text-center sm:text-left">
          <div className="flex flex-col items-center sm:items-start">
            <CompanyLogo logoUrl={logoUrl} companyName={companyName} />
          </div>
          <h1 className="text-lg font-semibold leading-tight tracking-tight text-slate-900 sm:text-xl">
            {companyName || "Company"}
          </h1>
          <p className="mt-2 text-xs font-semibold uppercase tracking-[0.12em] text-slate-600">
            Statement of Cash Flows
          </p>
          <p className="mt-1.5 text-sm text-slate-800">
            For the period {formatBsDate(periodFrom)} – {formatBsDate(periodTo)}
          </p>
        </div>

        <div className="shrink-0 text-center text-xs leading-relaxed text-slate-500 sm:text-right">
          <p className="font-semibold uppercase tracking-wide text-slate-600">
            Currency: {currency}
          </p>
          {fiscalYear ? <p className="mt-1">Fiscal year: {fiscalYear}</p> : null}
          {generatedBy ? (
            <p className="mt-1">Generated by {generatedBy}</p>
          ) : null}
          {printedAt ? <p className="mt-1">{printedAt}</p> : null}
        </div>
      </div>
    </header>
  );
}

const SECTION_META = {
  operating: {
    icon: Wallet,
    title: "Operating activities",
    hint: "Cash generated from day-to-day business operations",
    rowLabel: "Net cash from operating activities",
  },
  investing: {
    icon: TrendingUp,
    title: "Investing activities",
    hint: "Cash used for or generated from acquiring and disposing of assets",
    rowLabel: "Net cash from investing activities",
  },
  financing: {
    icon: Landmark,
    title: "Financing activities",
    hint: "Cash flows between the business and its owners or lenders",
    rowLabel: "Net cash from financing activities",
  },
};

function SectionHeadingRow({ section }) {
  const meta = SECTION_META[section];
  const Icon = meta.icon;
  return (
    <tr className="cf-section-heading">
      <td colSpan={2} className="border-b border-slate-300 pb-1 pt-4 print:pt-2">
        <div className="flex items-center gap-2">
          <span className="flex size-5 shrink-0 items-center justify-center rounded border border-slate-200 bg-slate-50 text-slate-500 print:hidden">
            <Icon className="size-3" strokeWidth={2} />
          </span>
          <span className="text-xs font-bold uppercase tracking-[0.1em] text-slate-900">
            {meta.title}
          </span>
        </div>
        <p className="mt-0.5 pl-7 text-xs text-slate-400 print:hidden">{meta.hint}</p>
      </td>
    </tr>
  );
}

function ActivityRow({ label, amount }) {
  const positive = Number(amount) >= 0;
  return (
    <tr className="cf-activity-row border-t border-slate-200">
      <td className="py-2 pl-7 text-sm text-slate-700">{label}</td>
      <td
        className={cn(
          "balance-sheet-amount py-2 text-right text-sm font-semibold tabular-nums",
          positive ? "text-slate-900" : "text-rose-700",
        )}
      >
        {formatBsAmount(amount) || "—"}
      </td>
    </tr>
  );
}

function SpacerRow() {
  return (
    <tr aria-hidden>
      <td colSpan={2} className="h-2" />
    </tr>
  );
}

function GrandTotalRow({ label, amount }) {
  const positive = Number(amount) >= 0;
  return (
    <tr className="cf-grand-total border-y-[3px] border-double border-slate-900">
      <td className="py-2.5 pl-3 text-sm font-semibold text-slate-900">{label}</td>
      <td
        className={cn(
          "balance-sheet-amount py-2.5 text-right text-sm font-bold tabular-nums",
          positive ? "text-emerald-700" : "text-rose-700",
        )}
      >
        {formatBsAmount(amount) || "—"}
      </td>
    </tr>
  );
}

function ClosingNotice({ netChange, currency }) {
  const positive = Number(netChange) >= 0;
  const Icon = positive ? TrendingUp : TrendingDown;

  return (
    <div
      className={cn(
        "cf-closing-notice mx-6 flex items-center justify-center gap-2 border px-4 py-2.5 print:mx-0 print:px-4 print:py-1.5 sm:mx-8",
        positive
          ? "border-emerald-200 bg-emerald-50/60"
          : "border-rose-200 bg-rose-50/60",
      )}
    >
      <Icon
        className={cn("size-3.5 shrink-0", positive ? "text-emerald-600" : "text-rose-600")}
        aria-hidden
      />
      <p
        className={cn(
          "text-sm font-semibold",
          positive ? "text-emerald-800" : "text-rose-800",
        )}
      >
        Cash {positive ? "increased" : "decreased"} by{" "}
        {formatBsAmount(Math.abs(Number(netChange) || 0)) || "0.00"} {currency} during this
        period.
      </p>
    </div>
  );
}

function StatementFooter() {
  return (
    <footer className="balance-sheet-footer border-t border-slate-200 px-6 py-3 print:px-4 print:py-2 sm:px-8">
      <div className="flex flex-col items-center justify-between gap-3 sm:flex-row sm:items-center">
        <div className="flex items-center gap-2">
          <img
            src={FINVOROO_LOGO}
            alt=""
            className="size-6 shrink-0 object-contain"
          />
          <span className="text-xs font-semibold tracking-tight text-slate-800">
            Finvoroo ERP
          </span>
        </div>
        <p className="text-center text-xs leading-relaxed text-slate-500 sm:text-right">
          Unaudited — For management purposes only
        </p>
      </div>
    </footer>
  );
}

export function CashFlowStatement({
  companyName,
  logoUrl,
  periodFrom,
  periodTo,
  currency,
  fiscalYear,
  generatedBy,
  printedAt,
  operating,
  investing,
  financing,
  netChange,
}) {
  return (
    <div className="cash-flow-statement bg-white">
      <StatementHeader
        companyName={companyName}
        logoUrl={logoUrl}
        periodFrom={periodFrom}
        periodTo={periodTo}
        currency={currency}
        fiscalYear={fiscalYear}
        generatedBy={generatedBy}
        printedAt={printedAt}
      />

      <div className="px-6 py-5 print:px-4 print:py-2 sm:px-8 sm:py-6">
        <div className="overflow-x-auto">
          <table className="cash-flow-table w-full min-w-[420px] border-collapse">
            <colgroup>
              <col />
              <col style={{ width: "9rem" }} />
            </colgroup>
            <tbody>
              <SectionHeadingRow section="operating" />
              <ActivityRow label={SECTION_META.operating.rowLabel} amount={operating} />

              <SpacerRow />

              <SectionHeadingRow section="investing" />
              <ActivityRow label={SECTION_META.investing.rowLabel} amount={investing} />

              <SpacerRow />

              <SectionHeadingRow section="financing" />
              <ActivityRow label={SECTION_META.financing.rowLabel} amount={financing} />

              <SpacerRow />

              <GrandTotalRow
                label={
                  Number(netChange) >= 0
                    ? "Net increase in cash"
                    : "Net decrease in cash"
                }
                amount={netChange}
              />
            </tbody>
          </table>
        </div>
      </div>

      <div className="cash-flow-closing">
        <ClosingNotice netChange={netChange} currency={currency} />
        <StatementFooter />
      </div>
    </div>
  );
}
