import { Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { ReportDateRangePicker } from './ReportDateRangePicker';
import { cn } from '@/lib/utils';
import { categoryLabel } from './CategoryTradingPartnerCards';
import { reportStickySheetHeaderClass } from './report-sticky';
import { STATEMENT_AMOUNT_COL } from './report-typography';

const FINVOROO_LOGO = '/media/app/finvoroo.svg';
const AMOUNT_COL = STATEMENT_AMOUNT_COL;

/**
 * Statement amount.
 *
 * Negatives carry a minus sign rather than the accountant's parentheses. The
 * balance sheet uses brackets because it is read by bookkeepers; this report is
 * read by the pharmacist who owns the shop, and "(174,850.08)" does not say
 * "loss" to them the way "−174,850.08" does.
 *
 * Zero renders as an em dash, matching the statement rows on the financial
 * summary, so an empty line reads as empty rather than as a real zero.
 */
function formatAmount(value, { currency, dash = false } = {}) {
  const n = Number(value);
  if (!Number.isFinite(n)) return dash ? '—' : '0.00';
  if (dash && Math.abs(n) < 0.005) return '—';

  const formatted = new Intl.NumberFormat('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(Math.abs(n));

  const core = n < -0.004 ? `\u2212${formatted}` : formatted;

  return currency ? `${core} ${currency}` : core;
}

function isNegative(value) {
  const n = Number(value);

  return Number.isFinite(n) && n < -0.004;
}

/** Company block, period and provenance — the masthead of a printed statement. */
function StatementHeader({
  companyName,
  logoUrl,
  periodFrom,
  periodTo,
  currency,
  generatedBy,
  printedAt,
}) {
  return (
    <header
      className={cn(
        'border-b border-slate-200 px-6 py-6 print:px-4 print:py-3 sm:px-8',
        reportStickySheetHeaderClass,
      )}
    >
      <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
        <div className="min-w-0 flex-1 text-center sm:text-left">
          <div className="flex flex-col items-center sm:items-start">
            <CompanyLogo logoUrl={logoUrl} companyName={companyName} />
          </div>
          <h1 className="text-lg font-semibold leading-tight tracking-tight text-slate-900 sm:text-xl">
            {companyName || 'Company'}
          </h1>
          <p className="mt-2 text-xs font-semibold uppercase tracking-[0.12em] text-slate-600">
            Category Sales &amp; Purchases
          </p>
          {periodFrom && periodTo ? (
            <p className="mt-1.5 text-sm text-slate-800">
              For period {periodFrom} – {periodTo}
            </p>
          ) : null}
        </div>

        <div className="shrink-0 text-center text-xs leading-relaxed text-slate-500 sm:text-right">
          <p className="font-semibold uppercase tracking-wide text-slate-600">
            Currency: {currency}
          </p>
          {generatedBy ? <p className="mt-1">Generated by {generatedBy}</p> : null}
          {printedAt ? <p className="mt-1">{printedAt}</p> : null}
        </div>
      </div>
    </header>
  );
}

function CompanyLogo({ logoUrl, companyName }) {
  if (logoUrl) {
    return (
      <img
        src={logoUrl}
        alt=""
        className="mb-3 h-12 w-auto max-w-[160px] object-contain print:mb-1 print:h-8 print:max-w-[120px]"
      />
    );
  }

  const words = String(companyName || '')
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  const initials =
    words.length >= 2
      ? `${words[0][0] ?? ''}${words[1][0] ?? ''}`.toUpperCase()
      : (words[0] ?? 'C').slice(0, 2).toUpperCase();

  return (
    <div
      aria-hidden
      className="mb-3 flex size-10 items-center justify-center border border-slate-300 text-xs font-semibold tracking-wide text-slate-600"
    >
      {initials}
    </div>
  );
}

function SectionHeading({ title, subtitle }) {
  return (
    <div className="mb-4 print:mb-2">
      <h3 className="border-b border-slate-900 pb-1.5 text-xs font-bold uppercase tracking-[0.1em] text-slate-900 print:pb-1">
        {title}
      </h3>
      {subtitle ? <p className="mt-1 text-xs text-slate-500">{subtitle}</p> : null}
    </div>
  );
}

function StatementSection({ title, subtitle, children, divided = true }) {
  return (
    <section
      className={cn(
        'px-6 py-5 print:px-4 print:py-2 sm:px-8 sm:py-6',
        divided && 'border-t border-slate-200',
      )}
    >
      <SectionHeading title={title} subtitle={subtitle} />
      {children}
    </section>
  );
}

/** A plain label/amount line — the unit every statement here is built from. */
function StatementRow({ label, amount, currency, indent = false }) {
  return (
    <div
      className={cn(
        'flex items-center gap-3 py-1 leading-snug print:py-0',
        indent && 'pl-3',
      )}
    >
      <div className="min-w-0 flex-1 whitespace-nowrap text-sm text-slate-700">{label}</div>
      <span className={cn(AMOUNT_COL, isNegative(amount) && 'text-red-600')}>
        {formatAmount(amount, { currency, dash: true })}
      </span>
    </div>
  );
}

function SubtotalRow({ label, amount, currency }) {
  return (
    <div className="mt-2 flex items-baseline gap-2 border-t border-slate-300 pt-2">
      <span className="min-w-0 flex-1 text-sm font-semibold text-slate-900">{label}</span>
      <span
        className={cn(AMOUNT_COL, 'font-semibold', isNegative(amount) && 'text-red-600')}
      >
        {formatAmount(amount, { currency, dash: true })}
      </span>
    </div>
  );
}

function GrandTotalRow({ label, amount, currency }) {
  return (
    <div className="flex items-baseline gap-2 border-t-[3px] border-double border-slate-900 py-2.5 print:py-2">
      <span className="min-w-0 flex-1 text-sm font-semibold text-slate-900">{label}</span>
      <span
        className={cn(AMOUNT_COL, 'text-sm font-bold', isNegative(amount) && 'text-red-600')}
      >
        {formatAmount(amount, { currency, dash: true })}
      </span>
    </div>
  );
}

function StatementFooter() {
  return (
    <footer className="border-t border-slate-200 px-6 py-3 print:px-4 print:py-2 sm:px-8">
      <div className="flex flex-col items-center justify-between gap-3 sm:flex-row sm:items-center">
        <div className="flex items-center gap-2">
          <img src={FINVOROO_LOGO} alt="" className="size-6 shrink-0 object-contain" />
          <span className="text-xs font-semibold tracking-tight text-slate-800">
            Finvoroo ERP
          </span>
        </div>
        <p className="text-center text-xs leading-relaxed text-slate-500 sm:text-right">
          Unaudited — For management purposes only
        </p>
      </div>
    </footer>
  );
}

export function CategoryTradingToolbar({
  from,
  to,
  onRangeChange,
  onApply,
  loading,
  includeExpenses,
  onIncludeExpensesChange,
}) {
  return (
    <div className="no-print flex flex-col gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3 shadow-sm sm:flex-row sm:items-center sm:justify-between">
      <div className="flex flex-wrap items-center gap-2">
        <ReportDateRangePicker
          from={from}
          to={to}
          onChange={onRangeChange}
          disabled={loading}
          className="h-9"
        />
        <Button
          size="sm"
          onClick={onApply}
          disabled={loading}
          className="h-9 bg-emerald-600 px-4 hover:bg-emerald-700"
        >
          {loading ? <Loader2 className="size-4 animate-spin" /> : 'Apply'}
        </Button>
      </div>

      <div className="flex items-center gap-3 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2">
        <span className="text-sm font-medium text-slate-700">Include expenses</span>
        <Switch
          checked={includeExpenses}
          onCheckedChange={onIncludeExpensesChange}
          aria-label="Include operational expenses"
        />
        <span
          className={cn(
            'min-w-[2rem] text-xs font-bold uppercase tracking-wide',
            includeExpenses ? 'text-emerald-700' : 'text-slate-400',
          )}
        >
          {includeExpenses ? 'On' : 'Off'}
        </span>
      </div>
    </div>
  );
}

export function CategoryTradingReportView({
  companyName,
  logoUrl,
  periodFrom,
  periodTo,
  currency,
  rows = [],
  totals = {},
  expenses = null,
  includeExpenses = false,
  printedAt,
  generatedBy,
}) {
  const grossProfit = Number(totals.gross_profit ?? totals.net_profit ?? 0);
  const expenseTotal = Number(totals.operating_expenses ?? expenses?.total ?? 0);
  const netAfterExpenses = Number(
    totals.net_profit_after_expenses ?? grossProfit - expenseTotal,
  );
  const expenseRows = expenses?.rows ?? [];

  return (
    <div className="category-trading-statement bg-white">
      <StatementHeader
        companyName={companyName}
        logoUrl={logoUrl}
        periodFrom={periodFrom}
        periodTo={periodTo}
        currency={currency}
        generatedBy={generatedBy}
        printedAt={printedAt}
      />

      {/* The summary is the same three lines the breakdown adds up to, so it is
          written as statement rows rather than cards — the arithmetic is the
          point, and boxing the figures apart hid it. */}
      <StatementSection title="Overall business summary" divided={false}>
        <StatementRow label="Total sales" amount={totals.sale} currency={currency} />
        <StatementRow label="Total purchases" amount={totals.purchase} currency={currency} />
        <SubtotalRow
          label={includeExpenses ? 'Gross profit (trading)' : 'Gross profit'}
          amount={grossProfit}
          currency={currency}
        />
        {includeExpenses ? (
          <>
            <StatementRow
              label="Operational expenses"
              amount={expenseTotal > 0.004 ? -expenseTotal : 0}
              currency={currency}
            />
            <GrandTotalRow
              label="Net profit — after expense"
              amount={netAfterExpenses}
              currency={currency}
            />
          </>
        ) : null}
      </StatementSection>

      <StatementSection
        title="Category trading breakdown"
        subtitle="Sales − Purchases = Gross profit"
      >
        <div className="overflow-x-auto">
          <table className="w-full min-w-[560px] border-collapse">
            <thead>
              <tr className="border-b border-slate-300 text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-500">
                <th className="py-1.5 pr-3 text-left font-semibold">Category name</th>
                <th className="px-3 py-1.5 text-right font-semibold">Total sale</th>
                <th className="px-3 py-1.5 text-right font-semibold">Total purchase</th>
                <th className="py-1.5 pl-3 text-right font-semibold">Gross profit</th>
              </tr>
            </thead>
            <tbody>
              {rows.length === 0 ? (
                <tr>
                  <td colSpan={4} className="py-8 text-center text-sm text-slate-400">
                    No category trading in this period.
                  </td>
                </tr>
              ) : (
                rows.map((row, index) => (
                  <tr key={row.category_id ?? `row-${index}`} className="leading-snug">
                    <td className="py-1 pr-3 text-sm text-slate-700">
                      {categoryLabel(row.category_name, row.category_code)}
                    </td>
                    <td className="px-3 py-1 text-right">
                      <span className={AMOUNT_COL}>
                        {formatAmount(row.sale, { dash: true })}
                      </span>
                    </td>
                    <td className="px-3 py-1 text-right">
                      <span className={AMOUNT_COL}>
                        {formatAmount(row.purchase, { dash: true })}
                      </span>
                    </td>
                    <td className="py-1 pl-3 text-right">
                      <span
                        className={cn(
                          AMOUNT_COL,
                          isNegative(row.net_profit) && 'text-red-600',
                        )}
                      >
                        {formatAmount(row.net_profit, { dash: true })}
                      </span>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
            {rows.length > 0 ? (
              <tfoot>
                <tr className="border-t-[3px] border-double border-slate-900">
                  <td className="py-2.5 pr-3 text-sm font-semibold text-slate-900 print:py-2">
                    Gross business total
                  </td>
                  <td className="px-3 py-2.5 text-right print:py-2">
                    <span className={cn(AMOUNT_COL, 'font-bold')}>
                      {formatAmount(totals.sale, { dash: true })}
                    </span>
                  </td>
                  <td className="px-3 py-2.5 text-right print:py-2">
                    <span className={cn(AMOUNT_COL, 'font-bold')}>
                      {formatAmount(totals.purchase, { dash: true })}
                    </span>
                  </td>
                  <td className="py-2.5 pl-3 text-right print:py-2">
                    <span
                      className={cn(
                        AMOUNT_COL,
                        'font-bold',
                        isNegative(grossProfit) && 'text-red-600',
                      )}
                    >
                      {formatAmount(grossProfit, { dash: true })}
                    </span>
                  </td>
                </tr>
              </tfoot>
            ) : null}
          </table>
        </div>
      </StatementSection>

      {includeExpenses ? (
        <StatementSection
          title="Operational expenses & final net profit"
          subtitle="Deducted from gross profit"
        >
          {expenseRows.length === 0 ? (
            <p className="py-6 text-center text-sm text-slate-400">
              No approved expenses in this period.
            </p>
          ) : (
            expenseRows.map((row, index) => (
              <StatementRow
                key={row.account_id ?? `expense-${index}`}
                label={row.label}
                amount={row.amount}
                indent
              />
            ))
          )}
          <SubtotalRow
            label="Total operational expenses"
            amount={expenseTotal > 0.004 ? -expenseTotal : 0}
            currency={currency}
          />
          <GrandTotalRow
            label="Final net profit"
            amount={netAfterExpenses}
            currency={currency}
          />
        </StatementSection>
      ) : null}

      <StatementFooter />
    </div>
  );
}
