import { cn } from "@/lib/utils";
import { reportStickySheetHeaderClass } from "./report-sticky";
import { formatBsDate } from "./BalanceSheetStatement";

const FINVOROO_LOGO = "/media/app/finvoroo.svg";

function CompanyLogo({ logoUrl, companyName }) {
  if (logoUrl) {
    return (
      <img
        src={logoUrl}
        alt=""
        className="mb-3 h-12 w-auto max-w-[160px] object-contain print:mb-1 print:h-8 print:max-w-[120px]"
      />
    );
  }

  const words = String(companyName || "")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  const initials =
    words.length >= 2
      ? `${words[0][0] ?? ""}${words[1][0] ?? ""}`.toUpperCase()
      : (words[0] ?? "C").slice(0, 2).toUpperCase();

  return (
    <div
      aria-hidden
      className="mb-3 flex size-10 items-center justify-center border border-slate-300 text-xs font-semibold tracking-wide text-slate-600"
    >
      {initials}
    </div>
  );
}

function formatMoney(value) {
  const n = Number(value);
  if (!Number.isFinite(n)) return "0.00";
  const formatted = new Intl.NumberFormat("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(Math.abs(n));
  return n < 0 ? `(${formatted})` : formatted;
}

function formatPct(value) {
  if (value === null || value === undefined || value === "") return "—";
  const n = Number(value);
  if (!Number.isFinite(n)) return "—";
  return `${n.toFixed(1)}%`;
}

function amountClass(value, { signed = false, emphasize = false } = {}) {
  const n = Number(value);
  const negative = Number.isFinite(n) && n < -0.004;
  const positive = signed && Number.isFinite(n) && n > 0.004;

  return cn(
    "text-right text-sm tabular-nums text-slate-900",
    emphasize && "font-semibold",
    negative && "text-red-700",
    positive && "text-emerald-800",
  );
}

function StatementHeader({
  companyName,
  logoUrl,
  periodFrom,
  periodTo,
  currency,
  fiscalYear,
  generatedBy,
  printedAt,
}) {
  return (
    <header
      className={cn(
        "balance-sheet-header border-b border-slate-200 px-6 py-6 print:py-3 sm:px-10 print:px-4",
        reportStickySheetHeaderClass,
      )}
    >
      <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
        <div className="min-w-0 flex-1 text-center sm:text-left">
          <div className="flex flex-col items-center sm:items-start">
            <CompanyLogo logoUrl={logoUrl} companyName={companyName} />
          </div>
          <h1 className="text-lg font-semibold leading-tight tracking-tight text-slate-900 sm:text-xl">
            {companyName || "Company"}
          </h1>
          <p className="mt-2 text-xs font-semibold uppercase tracking-[0.12em] text-slate-600">
            Category Sales &amp; Purchases
          </p>
          <p className="mt-1.5 text-sm text-slate-800">
            {formatBsDate(periodFrom)} – {formatBsDate(periodTo)}
          </p>
        </div>

        <div className="shrink-0 text-center text-xs leading-relaxed text-slate-500 sm:text-right">
          <p className="font-semibold uppercase tracking-wide text-slate-600">
            Currency: {currency}
          </p>
          {fiscalYear ? <p className="mt-1">Fiscal year: {fiscalYear}</p> : null}
          {generatedBy ? (
            <p className="mt-1">Generated by {generatedBy}</p>
          ) : null}
          {printedAt ? <p className="mt-1">{printedAt}</p> : null}
        </div>
      </div>
    </header>
  );
}

export function CategoryTradingStatement({
  companyName,
  logoUrl,
  periodFrom,
  periodTo,
  currency,
  fiscalYear,
  generatedBy,
  printedAt,
  rows = [],
  totals = {},
}) {
  return (
    <div className="category-trading-statement bg-white">
      <StatementHeader
        companyName={companyName}
        logoUrl={logoUrl}
        periodFrom={periodFrom}
        periodTo={periodTo}
        currency={currency}
        fiscalYear={fiscalYear}
        generatedBy={generatedBy}
        printedAt={printedAt}
      />

      <div className="px-6 py-5 print:px-4 print:py-3 sm:px-10 sm:py-6">
        <div className="mb-4 print:mb-2">
          <h3 className="border-b border-slate-900 pb-1.5 text-xs font-bold uppercase tracking-[0.1em] text-slate-900 print:pb-1">
            Trading by category
          </h3>
          <p className="mt-1 text-xs text-slate-500">
            Period purchases, sales, and net profit
          </p>
        </div>

        <table className="w-full table-fixed border-collapse">
          <colgroup>
            <col style={{ width: "32%" }} />
            <col style={{ width: "17%" }} />
            <col style={{ width: "17%" }} />
            <col style={{ width: "18%" }} />
            <col style={{ width: "16%" }} />
          </colgroup>
          <thead>
            <tr className="border-b border-slate-300 text-[11px] font-semibold uppercase tracking-[0.08em] text-slate-500">
              <th className="py-2 pr-3 text-left font-semibold">Category</th>
              <th className="py-2 pl-3 text-right font-semibold">Purchase</th>
              <th className="py-2 pl-3 text-right font-semibold">Sale</th>
              <th className="py-2 pl-3 text-right font-semibold">Net profit</th>
              <th className="py-2 pl-3 text-right font-semibold">Margin</th>
            </tr>
          </thead>
          <tbody>
            {rows.length === 0 ? (
              <tr>
                <td
                  colSpan={5}
                  className="py-10 text-center text-sm text-slate-400"
                >
                  No posted sales or purchases in this period.
                </td>
              </tr>
            ) : (
              rows.map((row) => (
                <tr
                  key={row.category_id ?? "uncategorized"}
                  className="border-b border-slate-100"
                >
                  <td className="py-2 pr-3 align-middle">
                    <p className="truncate text-sm text-slate-800">
                      {row.category_name}
                    </p>
                    {row.category_code ? (
                      <p className="font-mono text-[11px] text-slate-400">
                        {row.category_code}
                      </p>
                    ) : null}
                  </td>
                  <td className={cn("py-2 pl-3 align-middle", amountClass(row.purchase))}>
                    {formatMoney(row.purchase)}
                  </td>
                  <td className={cn("py-2 pl-3 align-middle", amountClass(row.sale))}>
                    {formatMoney(row.sale)}
                  </td>
                  <td
                    className={cn(
                      "py-2 pl-3 align-middle",
                      amountClass(row.net_profit, { signed: true }),
                    )}
                  >
                    {formatMoney(row.net_profit)}
                  </td>
                  <td
                    className={cn(
                      "py-2 pl-3 align-middle text-right text-sm tabular-nums text-slate-600",
                      Number(row.margin_percent) < 0 && "text-red-700",
                    )}
                  >
                    {formatPct(row.margin_percent)}
                  </td>
                </tr>
              ))
            )}
          </tbody>
          <tfoot>
            <tr className="border-t-2 border-slate-900">
              <td className="py-2.5 pr-3 text-sm font-bold uppercase tracking-wide text-slate-900">
                Total
              </td>
              <td
                className={cn(
                  "py-2.5 pl-3",
                  amountClass(totals.purchase, { emphasize: true }),
                )}
              >
                {formatMoney(totals.purchase)}
              </td>
              <td
                className={cn(
                  "py-2.5 pl-3",
                  amountClass(totals.sale, { emphasize: true }),
                )}
              >
                {formatMoney(totals.sale)}
              </td>
              <td
                className={cn(
                  "py-2.5 pl-3",
                  amountClass(totals.net_profit, {
                    emphasize: true,
                    signed: true,
                  }),
                )}
              >
                {formatMoney(totals.net_profit)}
              </td>
              <td
                className={cn(
                  "py-2.5 pl-3 text-right text-sm font-semibold tabular-nums text-slate-900",
                  Number(totals.margin_percent) < 0 && "text-red-700",
                )}
              >
                {formatPct(totals.margin_percent)}
              </td>
            </tr>
          </tfoot>
        </table>
      </div>

      <footer className="balance-sheet-footer border-t border-slate-200 px-6 py-4 print:px-4 print:py-2 sm:px-10">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
          <p className="max-w-xl text-xs leading-relaxed text-slate-500">
            Posted invoices, bills, credit notes, and vendor credits. Draft,
            cancelled, and void documents are excluded. Net profit is period
            sales minus period purchases by category.
          </p>
          <div className="flex items-center justify-between gap-6 sm:justify-end">
            <img
              src={FINVOROO_LOGO}
              alt="Finvoroo"
              className="h-5 w-auto opacity-70 print:h-4"
            />
            <p className="text-xs text-slate-500">
              Unaudited — For management purposes only
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
