import { CheckCircle2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { reportStickySheetHeaderClass } from "./report-sticky";
import { ReportDrillableStatementRow } from "./ReportDrillableStatementRow";
import { formatBsAmount, formatBsDate } from "./BalanceSheetStatement";
import { STATEMENT_AMOUNT_COL } from "./report-typography";
import { sortRowsByAccountCode } from "../report-account-sort";

const AMOUNT_COL = STATEMENT_AMOUNT_COL;

const FINVOROO_LOGO = "/media/app/finvoroo.svg";

function CompanyLogo({ logoUrl, companyName }) {
  if (logoUrl) {
    return (
      <img
        src={logoUrl}
        alt=""
        className="mb-3 h-12 w-auto max-w-[160px] object-contain print:mb-1 print:h-8 print:max-w-[120px]"
      />
    );
  }

  const words = String(companyName || "")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  const initials =
    words.length >= 2
      ? `${words[0][0] ?? ""}${words[1][0] ?? ""}`.toUpperCase()
      : (words[0] ?? "C").slice(0, 2).toUpperCase();

  return (
    <div
      aria-hidden
      className="mb-3 flex size-10 items-center justify-center border border-slate-300 text-xs font-semibold tracking-wide text-slate-600"
    >
      {initials}
    </div>
  );
}

function StatementHeader({
  companyName,
  logoUrl,
  periodFrom,
  periodTo,
  asOf,
  currency,
  fiscalYear,
  generatedBy,
  printedAt,
}) {
  return (
    <header className={cn(
      "balance-sheet-header border-b border-slate-200 px-6 py-6 print:py-3 sm:px-8 print:px-4",
      reportStickySheetHeaderClass,
    )}>
      <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
        <div className="min-w-0 flex-1 text-center sm:text-left">
          <div className="flex flex-col items-center sm:items-start">
            <CompanyLogo logoUrl={logoUrl} companyName={companyName} />
          </div>
          <h1 className="text-lg font-semibold leading-tight tracking-tight text-slate-900 sm:text-xl">
            {companyName || "Company"}
          </h1>
          <p className="mt-2 text-xs font-semibold uppercase tracking-[0.12em] text-slate-600">
            Financial Summary
          </p>
          <p className="mt-1.5 text-sm text-slate-800">
            Balance sheet as of {formatBsDate(asOf)}
          </p>
          {periodFrom && periodTo ? (
            <p className="mt-1 text-xs text-slate-500">
              Profit &amp; loss for period {formatBsDate(periodFrom)} –{" "}
              {formatBsDate(periodTo)}
            </p>
          ) : null}
        </div>

        <div className="shrink-0 text-center text-xs leading-relaxed text-slate-500 sm:text-right">
          <p className="font-semibold uppercase tracking-wide text-slate-600">
            Currency: {currency}
          </p>
          {fiscalYear ? <p className="mt-1">Fiscal year: {fiscalYear}</p> : null}
          {generatedBy ? (
            <p className="mt-1">Generated by {generatedBy}</p>
          ) : null}
          {printedAt ? <p className="mt-1">{printedAt}</p> : null}
        </div>
      </div>
    </header>
  );
}

function ColumnHeading({ title, subtitle }) {
  return (
    <div className="mb-4 print:mb-2">
      <h3 className="border-b border-slate-900 pb-1.5 text-xs font-bold uppercase tracking-[0.1em] text-slate-900 print:pb-1">
        {title}
      </h3>
      {subtitle ? (
        <p className="mt-1 text-xs text-slate-500">{subtitle}</p>
      ) : null}
    </div>
  );
}

function StatementRow({ label, amount, indent = false, computed = false }) {
  const formatted = formatBsAmount(amount);

  return (
    <div
      className={cn(
        "balance-sheet-row flex items-center gap-3 py-1 leading-snug print:py-0",
        indent && "pl-3",
      )}
    >
      <div className="min-w-0 flex-1 whitespace-nowrap text-sm text-slate-700">
        {label}
        {computed ? (
          <span className="ml-1 text-xs text-slate-400">(Computed)</span>
        ) : null}
      </div>
      <span className={cn(AMOUNT_COL, !formatted && "text-slate-300")}>
        {formatted || "—"}
      </span>
    </div>
  );
}

function AccountRow({ row, workspaceId, period, showCodes, amountKey = "balance" }) {
  const amount = row[amountKey];

  return (
    <ReportDrillableStatementRow
      workspaceId={workspaceId}
      accountId={row.account_id}
      from={period?.from}
      to={period?.to}
      className="balance-sheet-row flex items-center gap-3 py-1 pl-3 leading-snug print:py-0"
    >
      <div className="flex min-w-0 flex-1 items-center gap-1.5 text-sm text-slate-700">
        {showCodes && row.code ? (
          <span className="balance-sheet-code w-[3.5rem] shrink-0 font-mono text-xs text-slate-400 sm:w-[4rem]">
            {row.code}
          </span>
        ) : null}
        <span className="min-w-0 whitespace-nowrap text-slate-700 underline-offset-2 group-hover/drill:text-slate-900 group-hover/drill:underline">
          {row.name || "—"}
        </span>
      </div>
      <span className={cn(AMOUNT_COL, !formatBsAmount(amount) && "text-slate-300")}>
        {formatBsAmount(amount) || "—"}
      </span>
    </ReportDrillableStatementRow>
  );
}

function SubtotalRow({ label, amount, bold = false }) {
  return (
    <div className="balance-sheet-subtotal balance-sheet-row mt-2 flex items-baseline gap-2 border-t border-slate-300 pt-2">
      <span
        className={cn(
          "min-w-0 flex-1 text-sm text-slate-700",
          bold ? "font-semibold text-slate-900" : "font-semibold",
        )}
      >
        {label}
      </span>
      <span className={cn(AMOUNT_COL, "font-semibold")}>
        {formatBsAmount(amount) || "—"}
      </span>
    </div>
  );
}

function GrandTotalRow({ label, amount }) {
  return (
    <div className="balance-sheet-row flex items-baseline gap-2 border-t-[3px] border-double border-slate-900 py-2.5 print:py-2">
      <span className="min-w-0 flex-1 text-sm font-semibold text-slate-900">
        {label}
      </span>
      <span className={cn(AMOUNT_COL, "text-sm font-bold")}>
        {formatBsAmount(amount) || "—"}
      </span>
    </div>
  );
}

function SubsectionBlock({ title, children, subtotal, subtotalLabel }) {
  if (!children && subtotal == null) return null;

  return (
    <div className="balance-sheet-subsection">
      {title ? (
        <h4 className="mb-1.5 text-xs font-semibold uppercase tracking-[0.1em] text-slate-600">
          {title}
        </h4>
      ) : null}
      <div>{children}</div>
      {subtotal != null ? (
        <SubtotalRow label={subtotalLabel || `Total ${title}`} amount={subtotal} />
      ) : null}
    </div>
  );
}

function sumRows(rows, key = "balance") {
  return rows.reduce((s, r) => s + Number(r[key] || 0), 0);
}

function toSubtotalLabel(title) {
  if (!title) return "Total";
  return `Total ${title.charAt(0).toLowerCase()}${title.slice(1)}`;
}

function BalanceSheetColumn({
  assetGroups,
  liabilityGroups,
  equityGroups,
  retainedEarnings,
  priorPeriodEarnings,
  totalAssets,
  liabilitiesPlusEquity,
  workspaceId,
  period,
  showCodes,
  asOf,
}) {
  const activeAssetGroups = assetGroups.filter((g) => g.rows.length > 0);
  const activeLiabGroups = liabilityGroups.filter((g) => g.rows.length > 0);
  const capitalGroup = equityGroups.find((g) => g.key === "capital");
  const drawingsGroup = equityGroups.find((g) => g.key === "drawings");
  const retainedGroup = equityGroups.find((g) => g.key === "retained");
  const showPrior = Math.abs(Number(priorPeriodEarnings) || 0) >= 0.005;

  const equityAccountRows = [
    ...(capitalGroup?.rows || []),
    ...(drawingsGroup?.rows || []),
    ...(retainedGroup?.rows || []),
  ];

  const totalLiabilities = activeLiabGroups.reduce(
    (s, g) => s + sumRows(g.rows),
    0,
  );
  const totalEquity =
    sumRows(equityAccountRows) +
    (showPrior ? Number(priorPeriodEarnings) : 0) +
    Number(retainedEarnings || 0);

  const hasContent =
    activeAssetGroups.length > 0 ||
    activeLiabGroups.length > 0 ||
    equityAccountRows.length > 0 ||
    showPrior ||
    Math.abs(Number(retainedEarnings) || 0) >= 0.005;

  if (!hasContent) {
    return (
      <div className="balance-sheet-col min-w-0">
        <ColumnHeading title="Balance Sheet" subtitle={`As of ${formatBsDate(asOf)}`} />
        <p className="pl-3 text-sm text-slate-400">No balance sheet data</p>
      </div>
    );
  }

  return (
    <div className="balance-sheet-col min-w-0">
      <ColumnHeading title="Balance Sheet" subtitle={`As of ${formatBsDate(asOf)}`} />

      <div className="flex flex-col gap-5 print:gap-2">
        {activeAssetGroups.length > 0 ? (
          <div>
            <h4 className="mb-2 text-xs font-bold uppercase tracking-[0.1em] text-slate-900">
              Assets
            </h4>
            {activeAssetGroups.map((group) => (
              <SubsectionBlock
                key={group.key}
                title={group.label}
                subtotal={sumRows(group.rows)}
                subtotalLabel={toSubtotalLabel(group.label)}
              >
                {group.rows.map((row) => (
                  <AccountRow
                    key={row.account_id}
                    row={row}
                    workspaceId={workspaceId}
                    period={period}
                    showCodes={showCodes}
                  />
                ))}
              </SubsectionBlock>
            ))}
            <SubtotalRow label="Total assets" amount={totalAssets} bold />
          </div>
        ) : null}

        {activeLiabGroups.length > 0 || equityAccountRows.length > 0 || showPrior || Math.abs(Number(retainedEarnings) || 0) >= 0.005 ? (
          <div>
            <h4 className="mb-2 text-xs font-bold uppercase tracking-[0.1em] text-slate-900">
              Liabilities &amp; equity
            </h4>

            {activeLiabGroups.map((group) => (
              <SubsectionBlock
                key={group.key}
                title={group.label}
                subtotal={sumRows(group.rows)}
                subtotalLabel={toSubtotalLabel(group.label)}
              >
                {group.rows.map((row) => (
                  <AccountRow
                    key={row.account_id}
                    row={row}
                    workspaceId={workspaceId}
                    period={period}
                    showCodes={showCodes}
                  />
                ))}
              </SubsectionBlock>
            ))}

            {activeLiabGroups.length > 0 ? (
              <SubtotalRow label="Total liabilities" amount={totalLiabilities} />
            ) : null}

            {equityAccountRows.length > 0 ||
            showPrior ||
            Math.abs(Number(retainedEarnings) || 0) >= 0.005 ? (
              <div className="balance-sheet-subsection">
                <h4 className="mb-1.5 text-xs font-semibold uppercase tracking-[0.1em] text-slate-600">
                  Equity
                </h4>
                <div>
                  {equityAccountRows.map((row) => (
                    <AccountRow
                      key={row.account_id}
                      row={row}
                      workspaceId={workspaceId}
                      period={period}
                      showCodes={showCodes}
                    />
                  ))}
                  {showPrior ? (
                    <StatementRow
                      indent
                      computed
                      label="Prior period profit / loss (unclosed)"
                      amount={priorPeriodEarnings}
                    />
                  ) : null}
                  <StatementRow
                    indent
                    computed
                    label="Current year profit / loss"
                    amount={retainedEarnings}
                  />
                </div>
                <SubtotalRow label="Total equity" amount={totalEquity} />
              </div>
            ) : null}

            <GrandTotalRow
              label="Total liabilities & equity"
              amount={liabilitiesPlusEquity}
            />
          </div>
        ) : null}
      </div>
    </div>
  );
}

function ProfitLossColumn({
  profitLoss,
  workspaceId,
  period,
  showCodes,
  periodFrom,
  periodTo,
}) {
  const sections = profitLoss?.sections || {};
  const summary = profitLoss?.summary || {};

  const revenueRows = sortRowsByAccountCode(sections.revenue?.rows || []);
  const otherIncomeRows = sortRowsByAccountCode(sections.other_income?.rows || []);
  const cogsRows = sortRowsByAccountCode(sections.cogs?.rows || []);
  const operatingRows = sortRowsByAccountCode(sections.operating_expenses?.rows || []);
  const otherExpenseRows = sortRowsByAccountCode(sections.other_expenses?.rows || []);

  const totalRevenue = summary.total_revenue ?? sumRows(revenueRows, "amount");
  const totalOtherIncome =
    summary.total_other_income ?? sumRows(otherIncomeRows, "amount");
  const totalIncome = totalRevenue + totalOtherIncome;
  const totalCogs = summary.total_cogs ?? sumRows(cogsRows, "amount");
  const grossProfit = summary.gross_profit ?? totalIncome - totalCogs;
  const totalOperating =
    summary.total_operating_expenses ?? sumRows(operatingRows, "amount");
  const totalOtherExpenses =
    summary.total_other_expenses ?? sumRows(otherExpenseRows, "amount");
  const totalExpenses = totalOperating + totalOtherExpenses;
  const netIncome =
    summary.net_income ?? grossProfit - totalExpenses;
  const isProfit = netIncome >= 0;

  if (!profitLoss) {
    return (
      <div className="balance-sheet-col min-w-0">
        <ColumnHeading
          title="Profit & Loss"
          subtitle={`For period ${formatBsDate(periodFrom)} – ${formatBsDate(periodTo)}`}
        />
        <p className="pl-3 text-sm text-slate-400">No profit & loss data</p>
      </div>
    );
  }

  const hasIncome =
    revenueRows.length > 0 ||
    otherIncomeRows.length > 0 ||
    Math.abs(totalIncome) >= 0.005;
  const hasCogs = cogsRows.length > 0 || Math.abs(totalCogs) >= 0.005;
  const hasExpenses =
    operatingRows.length > 0 ||
    otherExpenseRows.length > 0 ||
    Math.abs(totalExpenses) >= 0.005;

  return (
    <div className="balance-sheet-col min-w-0">
      <ColumnHeading
        title="Profit & Loss"
        subtitle={`For period ${formatBsDate(periodFrom)} – ${formatBsDate(periodTo)}`}
      />

      <div className="flex flex-col gap-5 print:gap-2">
        {hasIncome ? (
          <div>
            <h4 className="mb-2 text-xs font-bold uppercase tracking-[0.1em] text-slate-900">
              Income
            </h4>
            {revenueRows.length > 0 ? (
              <SubsectionBlock title="Revenue">
                {revenueRows.map((row) => (
                  <AccountRow
                    key={row.account_id}
                    row={row}
                    workspaceId={workspaceId}
                    period={period}
                    showCodes={showCodes}
                    amountKey="amount"
                  />
                ))}
              </SubsectionBlock>
            ) : null}
            {otherIncomeRows.length > 0 ? (
              <SubsectionBlock title="Other income">
                {otherIncomeRows.map((row) => (
                  <AccountRow
                    key={row.account_id}
                    row={row}
                    workspaceId={workspaceId}
                    period={period}
                    showCodes={showCodes}
                    amountKey="amount"
                  />
                ))}
              </SubsectionBlock>
            ) : null}
            <SubtotalRow label="Total income" amount={totalIncome} bold />
          </div>
        ) : null}

        {hasCogs ? (
          cogsRows.length > 0 ? (
            <SubsectionBlock
              title="Cost of goods sold"
              subtotal={totalCogs}
              subtotalLabel="Total cost of goods sold"
            >
              {cogsRows.map((row) => (
                <AccountRow
                  key={row.account_id}
                  row={row}
                  workspaceId={workspaceId}
                  period={period}
                  showCodes={showCodes}
                  amountKey="amount"
                />
              ))}
            </SubsectionBlock>
          ) : (
            <SubtotalRow label="Total cost of goods sold" amount={totalCogs} />
          )
        ) : null}

        <SubtotalRow label="Gross profit" amount={grossProfit} bold />

        {hasExpenses ? (
          <div>
            <h4 className="mb-2 text-xs font-bold uppercase tracking-[0.1em] text-slate-900">
              Expenses
            </h4>
            {operatingRows.length > 0 ? (
              <SubsectionBlock title="Operating expenses">
                {operatingRows.map((row) => (
                  <AccountRow
                    key={row.account_id}
                    row={row}
                    workspaceId={workspaceId}
                    period={period}
                    showCodes={showCodes}
                    amountKey="amount"
                  />
                ))}
              </SubsectionBlock>
            ) : null}
            {otherExpenseRows.length > 0 ? (
              <SubsectionBlock title="Other expenses">
                {otherExpenseRows.map((row) => (
                  <AccountRow
                    key={row.account_id}
                    row={row}
                    workspaceId={workspaceId}
                    period={period}
                    showCodes={showCodes}
                    amountKey="amount"
                  />
                ))}
              </SubsectionBlock>
            ) : null}
            <SubtotalRow label="Total expenses" amount={totalExpenses} bold />
          </div>
        ) : null}

        <GrandTotalRow
          label={isProfit ? "Net profit for the period" : "Net loss for the period"}
          amount={netIncome}
        />
      </div>
    </div>
  );
}

function BalanceBalancedNotice({ isBalanced }) {
  if (!isBalanced) return null;

  return (
    <div className="balance-sheet-balanced mx-6 border border-emerald-200 bg-emerald-50/60 px-4 py-2.5 print:mx-0 print:px-4 print:py-1.5 sm:mx-8">
      <p className="flex items-center justify-center gap-2 text-sm font-semibold text-emerald-800">
        <CheckCircle2 className="size-3.5 shrink-0 text-emerald-600" aria-hidden />
        Balance sheet balances — total assets equal total liabilities and equity.
      </p>
    </div>
  );
}

function BalanceValidation({
  isBalanced,
  balanceDifference,
  currency,
  unbalancedJournalCount,
}) {
  if (isBalanced) return null;

  return (
    <div className="balance-sheet-status no-print mx-6 border border-slate-400 bg-slate-50 px-4 py-3 sm:mx-8">
      <p className="text-sm font-semibold text-slate-900">
        Balance sheet out of balance
      </p>
      <p className="mt-1 text-sm leading-relaxed text-slate-700">
        Assets and liabilities + equity differ by{" "}
        <span className="font-semibold tabular-nums text-red-800">
          {formatBsAmount(balanceDifference)} {currency}
        </span>
        .
        {unbalancedJournalCount > 0
          ? ` ${unbalancedJournalCount} journal entr${unbalancedJournalCount === 1 ? "y has" : "ies have"} debit ≠ credit through this date.`
          : " Review inactive accounts with balances and source-document rounding."}
      </p>
    </div>
  );
}

function StatementFooter() {
  return (
    <footer className="balance-sheet-footer border-t border-slate-200 px-6 py-3 print:px-4 print:py-2 sm:px-8">
      <div className="flex flex-col items-center justify-between gap-3 sm:flex-row sm:items-center">
        <div className="flex items-center gap-2">
          <img
            src={FINVOROO_LOGO}
            alt=""
            className="size-6 shrink-0 object-contain"
          />
          <span className="text-xs font-semibold tracking-tight text-slate-800">
            Finvoroo ERP
          </span>
        </div>
        <p className="text-center text-xs leading-relaxed text-slate-500 sm:text-right">
          Unaudited — For management purposes only
        </p>
      </div>
    </footer>
  );
}

export function FinancialSummaryStatement({
  companyName,
  logoUrl,
  periodFrom,
  periodTo,
  asOf,
  currency,
  fiscalYear,
  generatedBy,
  printedAt,
  assetGroups,
  liabilityGroups,
  equityGroups,
  retainedEarnings,
  priorPeriodEarnings,
  totalAssets,
  liabilitiesPlusEquity,
  isBalanced,
  balanceDifference,
  unbalancedJournalCount,
  profitLoss,
  workspaceId,
  period,
  showCodes = true,
}) {
  return (
    <div className="financial-summary-statement bg-white">
      <StatementHeader
        companyName={companyName}
        logoUrl={logoUrl}
        periodFrom={periodFrom}
        periodTo={periodTo}
        asOf={asOf}
        currency={currency}
        fiscalYear={fiscalYear}
        generatedBy={generatedBy}
        printedAt={printedAt}
      />

      <div className="financial-summary-columns balance-sheet-columns grid grid-cols-1 lg:grid-cols-2 lg:divide-x lg:divide-slate-300">
        <div className="px-6 py-5 print:px-4 print:py-2 sm:px-8 sm:py-6">
          <BalanceSheetColumn
            assetGroups={assetGroups}
            liabilityGroups={liabilityGroups}
            equityGroups={equityGroups}
            retainedEarnings={retainedEarnings}
            priorPeriodEarnings={priorPeriodEarnings}
            totalAssets={totalAssets}
            liabilitiesPlusEquity={liabilitiesPlusEquity}
            workspaceId={workspaceId}
            period={period}
            showCodes={showCodes}
            asOf={asOf}
          />
        </div>

        <div className="px-6 py-5 print:px-4 print:py-2 sm:px-8 sm:py-6">
          <ProfitLossColumn
            profitLoss={profitLoss}
            workspaceId={workspaceId}
            period={period}
            showCodes={showCodes}
            periodFrom={periodFrom}
            periodTo={periodTo}
          />
        </div>
      </div>

      <div className="balance-sheet-closing">
        <BalanceBalancedNotice isBalanced={isBalanced} />
        <BalanceValidation
          isBalanced={isBalanced}
          balanceDifference={balanceDifference}
          currency={currency}
          unbalancedJournalCount={unbalancedJournalCount}
        />
        <StatementFooter />
      </div>
    </div>
  );
}
