import { format, parseISO } from "date-fns";
import { GeneralLedgerTable } from "./GeneralLedgerTable";
import { PaidReferenceLegend } from "../ledger-paid-marker";

const FINVOROO_LOGO = "/media/app/finvoroo.svg";

function formatPeriodLine(periodFrom, periodTo) {
  try {
    const fromLabel = periodFrom
      ? format(parseISO(String(periodFrom).slice(0, 10)), "dd MMMM yyyy")
      : "…";
    const toLabel = periodTo
      ? format(parseISO(String(periodTo).slice(0, 10)), "dd MMMM yyyy")
      : "…";
    return `${fromLabel} – ${toLabel}`;
  } catch {
    return [periodFrom, periodTo].filter(Boolean).join(" – ");
  }
}

function CompanyLogo({ logoUrl, companyName }) {
  if (logoUrl) {
    return (
      <img
        src={logoUrl}
        alt=""
        className="h-7 w-auto max-w-[88px] shrink-0 object-contain print:h-6"
      />
    );
  }

  const words = String(companyName || "")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  const initials =
    words.length >= 2
      ? `${words[0][0] ?? ""}${words[1][0] ?? ""}`.toUpperCase()
      : (words[0] ?? "C").slice(0, 2).toUpperCase();

  return (
    <div
      aria-hidden
      className="flex size-7 shrink-0 items-center justify-center border border-slate-300 text-[10px] font-semibold tracking-wide text-slate-600"
    >
      {initials}
    </div>
  );
}

export function LedgerStatementPrintHeader({
  companyName,
  logoUrl,
  periodFrom,
  periodTo,
  currency,
  fiscalYear,
  generatedBy,
  printedAt,
  reportTitle,
  scopeLabel,
  pageLabel,
  activityLabel,
}) {
  const periodLine = formatPeriodLine(periodFrom, periodTo);
  const metaLine = [fiscalYear, activityLabel].filter(Boolean).join(" · ");
  const byLine = [generatedBy ? `Generated by ${generatedBy}` : null, printedAt]
    .filter(Boolean)
    .join(" · ");

  return (
    <header className="hidden border-b border-slate-200 px-5 py-2 print:block print:px-4 print:py-2 sm:px-6">
      <div className="flex items-center justify-between gap-4">
        <div className="flex min-w-0 items-center gap-2.5">
          <CompanyLogo logoUrl={logoUrl} companyName={companyName} />
          <div className="min-w-0">
            <div className="flex flex-wrap items-baseline gap-x-2">
              <h1 className="text-sm font-semibold leading-tight tracking-tight text-slate-900">
                {companyName || "Company"}
              </h1>
              <span className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">
                {reportTitle}
              </span>
            </div>
            {periodLine ? (
              <p className="text-xs leading-snug text-slate-700">{periodLine}</p>
            ) : null}
            {scopeLabel ? (
              <p className="text-[11px] leading-snug text-slate-500">
                {scopeLabel}
                {pageLabel ? <span> · {pageLabel}</span> : null}
              </p>
            ) : null}
          </div>
        </div>

        <div className="hidden shrink-0 text-right text-[11px] leading-snug text-slate-500 sm:block">
          <p>
            <span className="font-semibold uppercase tracking-wide text-slate-600">
              {currency}
            </span>
            {metaLine ? <span> · {metaLine}</span> : null}
          </p>
          {byLine ? <p>{byLine}</p> : null}
        </div>
      </div>
    </header>
  );
}

export function LedgerStatementPrintFooter() {
  return (
    <footer className="border-t border-slate-200 px-6 py-3 print:px-4 print:py-2 sm:px-8">
      <div className="flex flex-col items-center justify-between gap-3 sm:flex-row sm:items-center">
        <div className="flex items-center gap-2">
          <img
            src={FINVOROO_LOGO}
            alt=""
            className="size-6 shrink-0 object-contain"
          />
          <span className="text-xs font-semibold tracking-tight text-slate-800">
            Finvoroo ERP
          </span>
        </div>
        <p className="text-center text-xs leading-relaxed text-slate-500 sm:text-right">
          Unaudited — For management purposes only
        </p>
      </div>
    </footer>
  );
}

export function GeneralLedgerStatement({
  companyName,
  logoUrl,
  periodFrom,
  periodTo,
  currency,
  fiscalYear,
  generatedBy,
  printedAt,
  scopeLabel,
  pageLabel,
  reportTitle = "General Ledger",
  rows,
  loading,
  workspaceId,
  period,
  visibleColumns,
  reorderColumns,
  totals,
  recordCount,
  totalRecords,
  variant = "peachtree",
  columnWidths,
  onColumnResize,
  reportKey = "general_ledger",
}) {
  const isPeachtree = variant === "peachtree";
  const activityLabel =
    totalRecords != null && totalRecords !== recordCount
      ? `${recordCount} of ${totalRecords} line items on this page`
      : `${recordCount} ${recordCount === 1 ? "line item" : "line items"}`;

  return (
    <div className="general-ledger-statement bg-white">
      {isPeachtree ? (
        <LedgerStatementPrintHeader
          companyName={companyName}
          logoUrl={logoUrl}
          periodFrom={periodFrom}
          periodTo={periodTo}
          currency={currency}
          fiscalYear={fiscalYear}
          generatedBy={generatedBy}
          printedAt={printedAt}
          reportTitle={reportTitle}
          scopeLabel={scopeLabel}
          pageLabel={pageLabel}
          activityLabel={activityLabel}
        />
      ) : null}

      <GeneralLedgerTable
        rows={rows}
        loading={loading}
        workspaceId={workspaceId}
        period={period}
        currency={currency}
        visibleColumns={visibleColumns}
        reorderColumns={reorderColumns}
        variant={variant}
        totals={totals}
        enableColumnReorder={!isPeachtree}
        columnWidths={columnWidths}
        onColumnResize={onColumnResize}
        reportKey={reportKey}
      />

      {isPeachtree && rows.length > 0 ? (
        <div className="border-t border-slate-100 px-6 py-2 print:px-4 sm:px-8">
          <PaidReferenceLegend className="text-xs text-slate-500" />
        </div>
      ) : null}

      {isPeachtree ? <LedgerStatementPrintFooter /> : null}
    </div>
  );
}
