import { cn } from "@/lib/utils";
import { reportStickySheetHeaderClass } from "./report-sticky";
import { ReportDrillableAccountRow } from "./ReportDrillableAccountRow";
import { ReportDraggableTableHead } from "./ReportDraggableTableHead";
import { formatBsAmount, formatBsDate } from "./BalanceSheetStatement";
import { sortRowsByAccountCode } from "../report-account-sort";

const FINVOROO_LOGO = "/media/app/finvoroo.svg";

function fmtPct(value) {
  const n = Number(value);
  if (!Number.isFinite(n)) return "—";
  return `${n.toFixed(2)}%`;
}

function pctOf(n, base) {
  const num = Number(n);
  const den = Number(base);
  if (!Number.isFinite(num) || !Number.isFinite(den) || Math.abs(den) < 0.005) {
    return 0;
  }
  return (num / den) * 100;
}

function CompanyLogo({ logoUrl, companyName }) {
  if (logoUrl) {
    return (
      <img
        src={logoUrl}
        alt=""
        className="mb-3 h-12 w-auto max-w-[160px] object-contain print:mb-1 print:h-8 print:max-w-[120px]"
      />
    );
  }

  const words = String(companyName || "")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  const initials =
    words.length >= 2
      ? `${words[0][0] ?? ""}${words[1][0] ?? ""}`.toUpperCase()
      : (words[0] ?? "C").slice(0, 2).toUpperCase();

  return (
    <div
      aria-hidden
      className="mb-3 flex size-10 items-center justify-center border border-slate-300 text-xs font-semibold tracking-wide text-slate-600"
    >
      {initials}
    </div>
  );
}

function StatementHeader({
  companyName,
  logoUrl,
  periodFrom,
  periodTo,
  currency,
  fiscalYear,
  generatedBy,
  printedAt,
  documentTitle = "Profit & Loss Statement",
}) {
  return (
    <header className={cn(
      "balance-sheet-header border-b border-slate-200 px-6 py-6 print:py-3 sm:px-8 print:px-4",
      reportStickySheetHeaderClass,
    )}>
      <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
        <div className="min-w-0 flex-1 text-center sm:text-left">
          <div className="flex flex-col items-center sm:items-start">
            <CompanyLogo logoUrl={logoUrl} companyName={companyName} />
          </div>
          <h1 className="text-lg font-semibold leading-tight tracking-tight text-slate-900 sm:text-xl">
            {companyName || "Company"}
          </h1>
          <p className="mt-2 text-xs font-semibold uppercase tracking-[0.12em] text-slate-600">
            {documentTitle}
          </p>
          <p className="mt-1.5 text-sm text-slate-800">
            For the period {formatBsDate(periodFrom)} – {formatBsDate(periodTo)}
          </p>
        </div>

        <div className="shrink-0 text-center text-xs leading-relaxed text-slate-500 sm:text-right">
          <p className="font-semibold uppercase tracking-wide text-slate-600">
            Currency: {currency}
          </p>
          {fiscalYear ? <p className="mt-1">Fiscal year: {fiscalYear}</p> : null}
          {generatedBy ? (
            <p className="mt-1">Generated by {generatedBy}</p>
          ) : null}
          {printedAt ? <p className="mt-1">{printedAt}</p> : null}
        </div>
      </div>
    </header>
  );
}

function SectionHeadingRow({ title, colCount }) {
  return (
    <tr className="pl-section-heading">
      <td
        colSpan={colCount}
        className="border-b border-slate-300 pb-1 pt-4 text-xs font-bold uppercase tracking-[0.1em] text-slate-900 print:pt-2"
      >
        {title}
      </td>
    </tr>
  );
}

function EmptyRow({ message, colCount }) {
  return (
    <tr>
      <td colSpan={colCount} className="py-1 pl-3 text-sm italic text-slate-400">
        {message}
      </td>
    </tr>
  );
}

function AccountRow({
  row,
  workspaceId,
  period,
  visibleColumns,
  showCodes,
}) {
  const ytdAmount = row.ytd_amount ?? row.amount;
  const currentPct = row.pct ?? 0;
  const ytdPctVal = row.ytd_pct ?? 0;

  return (
    <ReportDrillableAccountRow
      workspaceId={workspaceId}
      accountId={row.account_id}
      from={period?.from}
      to={period?.to}
      className="pl-account-row"
    >
      {visibleColumns.map((col) => {
        switch (col.id) {
          case "name":
            return (
              <td key={col.id} className="py-1 pl-3 pr-2 align-middle">
                <div className="flex min-w-0 items-center gap-1.5 text-sm text-slate-700">
                  {showCodes && row.code ? (
                    <span className="balance-sheet-code w-[3.5rem] shrink-0 font-mono text-xs text-slate-400 sm:w-[4rem]">
                      {row.code}
                    </span>
                  ) : null}
                  <span className="min-w-0 whitespace-nowrap text-slate-700 underline-offset-2 group-hover/drill:text-slate-900 group-hover/drill:underline">
                    {row.name || "—"}
                  </span>
                </div>
              </td>
            );
          case "current_amount":
            return (
              <td
                key={col.id}
                className="balance-sheet-amount py-1 text-right text-sm tabular-nums text-slate-900"
              >
                {formatBsAmount(row.amount) || "—"}
              </td>
            );
          case "current_pct":
            return (
              <td
                key={col.id}
                className="py-1 text-right text-sm tabular-nums text-slate-500"
              >
                {fmtPct(currentPct)}
              </td>
            );
          case "ytd_amount":
            return (
              <td
                key={col.id}
                className="balance-sheet-amount py-1 text-right text-sm tabular-nums text-slate-900"
              >
                {formatBsAmount(ytdAmount) || "—"}
              </td>
            );
          case "ytd_pct":
            return (
              <td
                key={col.id}
                className="py-1 text-right text-sm tabular-nums text-slate-500"
              >
                {fmtPct(ytdPctVal)}
              </td>
            );
          default:
            return <td key={col.id} className="py-1" />;
        }
      })}
    </ReportDrillableAccountRow>
  );
}

function SubtotalRow({
  label,
  amount,
  pct,
  ytdAmount,
  ytdPct,
  visibleColumns,
  bold = false,
}) {
  return (
    <tr className="pl-subtotal-row border-t border-slate-300">
      {visibleColumns.map((col) => {
        switch (col.id) {
          case "name":
            return (
              <td
                key={col.id}
                className={cn(
                  "py-2 pl-3 text-sm text-slate-700",
                  bold ? "font-semibold text-slate-900" : "font-semibold",
                )}
              >
                {label}
              </td>
            );
          case "current_amount":
            return (
              <td
                key={col.id}
                className="balance-sheet-amount py-2 text-right text-sm font-semibold tabular-nums text-slate-900"
              >
                {formatBsAmount(amount) || "—"}
              </td>
            );
          case "current_pct":
            return (
              <td
                key={col.id}
                className="py-2 text-right text-sm font-semibold tabular-nums text-slate-600"
              >
                {fmtPct(pct)}
              </td>
            );
          case "ytd_amount":
            return (
              <td
                key={col.id}
                className="balance-sheet-amount py-2 text-right text-sm font-semibold tabular-nums text-slate-900"
              >
                {formatBsAmount(ytdAmount) || "—"}
              </td>
            );
          case "ytd_pct":
            return (
              <td
                key={col.id}
                className="py-2 text-right text-sm font-semibold tabular-nums text-slate-600"
              >
                {fmtPct(ytdPct)}
              </td>
            );
          default:
            return <td key={col.id} className="py-2" />;
        }
      })}
    </tr>
  );
}

function GrandTotalRow({
  label,
  amount,
  pct,
  ytdAmount,
  ytdPct,
  visibleColumns,
}) {
  return (
    <tr className="pl-grand-total border-y-[3px] border-double border-slate-900">
      {visibleColumns.map((col) => {
        switch (col.id) {
          case "name":
            return (
              <td
                key={col.id}
                className="py-2.5 pl-3 text-sm font-semibold text-slate-900"
              >
                {label}
              </td>
            );
          case "current_amount":
            return (
              <td
                key={col.id}
                className="balance-sheet-amount py-2.5 text-right text-sm font-bold tabular-nums text-slate-900"
              >
                {formatBsAmount(amount) || "—"}
              </td>
            );
          case "current_pct":
            return (
              <td
                key={col.id}
                className="py-2.5 text-right text-sm font-semibold tabular-nums text-slate-900"
              >
                {fmtPct(pct)}
              </td>
            );
          case "ytd_amount":
            return (
              <td
                key={col.id}
                className="balance-sheet-amount py-2.5 text-right text-sm font-bold tabular-nums text-slate-900"
              >
                {formatBsAmount(ytdAmount) || "—"}
              </td>
            );
          case "ytd_pct":
            return (
              <td
                key={col.id}
                className="py-2.5 text-right text-sm font-semibold tabular-nums text-slate-900"
              >
                {fmtPct(ytdPct)}
              </td>
            );
          default:
            return <td key={col.id} className="py-2.5" />;
        }
      })}
    </tr>
  );
}

function SpacerRow({ colCount }) {
  return (
    <tr aria-hidden>
      <td colSpan={colCount} className="h-2" />
    </tr>
  );
}

function StatementFooter() {
  return (
    <footer className="balance-sheet-footer border-t border-slate-200 px-6 py-3 print:px-4 print:py-2 sm:px-8">
      <div className="flex flex-col items-center justify-between gap-3 sm:flex-row sm:items-center">
        <div className="flex items-center gap-2">
          <img
            src={FINVOROO_LOGO}
            alt=""
            className="size-6 shrink-0 object-contain"
          />
          <span className="text-xs font-semibold tracking-tight text-slate-800">
            Finvoroo ERP
          </span>
        </div>
        <p className="text-center text-xs leading-relaxed text-slate-500 sm:text-right">
          Unaudited — For management purposes only
        </p>
      </div>
    </footer>
  );
}

export function ProfitLossStatement({
  companyName,
  logoUrl,
  periodFrom,
  periodTo,
  currency,
  fiscalYear,
  generatedBy,
  printedAt,
  sections,
  summary,
  workspaceId,
  period,
  visibleColumns,
  reorderColumns,
  showCodes = true,
  documentTitle = "Profit & Loss Statement",
}) {
  const colCount = visibleColumns.length;

  const revenue = summary.total_revenue ?? 0;
  const cogs = summary.total_cogs ?? 0;
  const grossProfit = summary.gross_profit ?? revenue - cogs;
  const operating = summary.total_operating_expenses ?? 0;
  const otherExp = summary.total_other_expenses ?? 0;
  const netIncome =
    summary.net_income ?? revenue - (cogs + operating + otherExp);
  const totalExp = operating + otherExp;

  const ytdRevenue = summary.ytd_total_revenue ?? revenue;
  const ytdCogs = summary.ytd_total_cogs ?? cogs;
  const ytdGrossProfit = summary.ytd_gross_profit ?? grossProfit;
  const ytdOperating = summary.ytd_total_operating_expenses ?? operating;
  const ytdOtherExp = summary.ytd_total_other_expenses ?? otherExp;
  const ytdNetIncome = summary.ytd_net_income ?? netIncome;
  const ytdTotalExp = ytdOperating + ytdOtherExp;

  const revPct = (n) => pctOf(n, revenue);
  const ytdRevPct = (n) => pctOf(n, ytdRevenue);

  const revenueRows = sortRowsByAccountCode(sections.revenue?.rows || []);
  const otherIncomeRows = sortRowsByAccountCode(sections.other_income?.rows || []);
  const cogsRows = sortRowsByAccountCode(sections.cogs?.rows || []);
  const opexRows = sortRowsByAccountCode(sections.operating_expenses?.rows || []);
  const otherExpenseRows = sortRowsByAccountCode(sections.other_expenses?.rows || []);

  return (
    <div className="profit-loss-statement bg-white">
      <StatementHeader
        companyName={companyName}
        logoUrl={logoUrl}
        periodFrom={periodFrom}
        periodTo={periodTo}
        currency={currency}
        fiscalYear={fiscalYear}
        generatedBy={generatedBy}
        printedAt={printedAt}
        documentTitle={documentTitle}
      />

      <div className="px-6 py-5 print:px-4 print:py-2 sm:px-8 sm:py-6">
        <div className="overflow-x-auto">
          <table className="profit-loss-table w-full min-w-[520px] border-collapse">
            <colgroup>
              {visibleColumns.map((col) => (
                <col
                  key={col.id}
                  style={
                    col.id === "name"
                      ? undefined
                      : col.id === "current_pct" || col.id === "ytd_pct"
                        ? { width: "72px" }
                        : { width: "7.5rem" }
                  }
                />
              ))}
            </colgroup>
            <thead>
              <ReportDraggableTableHead
                columns={visibleColumns}
                onReorder={reorderColumns}
                renderLabel={(col) => (
                  <span className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-600">
                    {col.label}
                  </span>
                )}
                isRightAligned={(col) => col.id !== "name"}
                getExtraClassName={() =>
                  "border-b border-slate-900 bg-white px-2 py-2 align-bottom print:py-1"
                }
              />
            </thead>
            <tbody>
              <SectionHeadingRow title="Revenue" colCount={colCount} />
              {revenueRows.length === 0 ? (
                <EmptyRow message="No revenue accounts" colCount={colCount} />
              ) : (
                revenueRows.map((row) => (
                  <AccountRow
                    key={row.account_id}
                    row={row}
                    workspaceId={workspaceId}
                    period={period}
                    visibleColumns={visibleColumns}
                    showCodes={showCodes}
                  />
                ))
              )}

              {otherIncomeRows.length > 0 ? (
                <>
                  <SectionHeadingRow title="Other income" colCount={colCount} />
                  {otherIncomeRows.map((row) => (
                    <AccountRow
                      key={row.account_id}
                      row={row}
                      workspaceId={workspaceId}
                      period={period}
                      visibleColumns={visibleColumns}
                      showCodes={showCodes}
                    />
                  ))}
                </>
              ) : null}

              <SubtotalRow
                label="Total revenue"
                amount={revenue}
                pct={100}
                ytdAmount={ytdRevenue}
                ytdPct={100}
                visibleColumns={visibleColumns}
                bold
              />

              <SpacerRow colCount={colCount} />

              <SectionHeadingRow title="Cost of goods sold" colCount={colCount} />
              {cogsRows.length === 0 ? (
                <EmptyRow message="No cost of goods sold accounts" colCount={colCount} />
              ) : (
                cogsRows.map((row) => (
                  <AccountRow
                    key={row.account_id}
                    row={row}
                    workspaceId={workspaceId}
                    period={period}
                    visibleColumns={visibleColumns}
                    showCodes={showCodes}
                  />
                ))
              )}
              <SubtotalRow
                label="Total cost of goods sold"
                amount={cogs}
                pct={revPct(cogs)}
                ytdAmount={ytdCogs}
                ytdPct={ytdRevPct(ytdCogs)}
                visibleColumns={visibleColumns}
              />

              <SpacerRow colCount={colCount} />

              <SubtotalRow
                label="Gross profit"
                amount={grossProfit}
                pct={revPct(grossProfit)}
                ytdAmount={ytdGrossProfit}
                ytdPct={ytdRevPct(ytdGrossProfit)}
                visibleColumns={visibleColumns}
                bold
              />

              <SpacerRow colCount={colCount} />

              <SectionHeadingRow title="Operating expenses" colCount={colCount} />
              {opexRows.length === 0 && otherExpenseRows.length === 0 ? (
                <EmptyRow message="No expense accounts" colCount={colCount} />
              ) : (
                <>
                  {opexRows.map((row) => (
                    <AccountRow
                      key={row.account_id}
                      row={row}
                      workspaceId={workspaceId}
                      period={period}
                      visibleColumns={visibleColumns}
                      showCodes={showCodes}
                    />
                  ))}
                  {otherExpenseRows.length > 0 ? (
                    <>
                      <SectionHeadingRow title="Other expenses" colCount={colCount} />
                      {otherExpenseRows.map((row) => (
                        <AccountRow
                          key={row.account_id}
                          row={row}
                          workspaceId={workspaceId}
                          period={period}
                          visibleColumns={visibleColumns}
                          showCodes={showCodes}
                        />
                      ))}
                    </>
                  ) : null}
                </>
              )}
              <SubtotalRow
                label="Total expenses"
                amount={totalExp}
                pct={revPct(totalExp)}
                ytdAmount={ytdTotalExp}
                ytdPct={ytdRevPct(ytdTotalExp)}
                visibleColumns={visibleColumns}
              />

              <SpacerRow colCount={colCount} />

              <GrandTotalRow
                label={netIncome >= 0 ? "Net profit for the period" : "Net loss for the period"}
                amount={netIncome}
                pct={revPct(netIncome)}
                ytdAmount={ytdNetIncome}
                ytdPct={ytdRevPct(ytdNetIncome)}
                visibleColumns={visibleColumns}
              />
            </tbody>
          </table>
        </div>
      </div>

      <StatementFooter />
    </div>
  );
}
