import {
  ArrowLeftRight,
  Briefcase,
  CreditCard,
  Factory,
  FileText,
  GitBranch,
  Package,
  Receipt,
  RotateCcw,
  Wallet,
} from 'lucide-react';

export const DOC_TYPE_META = {
  invoice: {
    label: 'Invoice',
    abbrev: 'IN',
    icon: FileText,
    accent: 'bg-blue-600',
    header: 'bg-blue-700',
    chip: 'bg-blue-50 text-blue-700 border-blue-200',
    iconBg: 'bg-blue-500/15 text-blue-600',
  },
  bill: {
    label: 'Bill',
    abbrev: 'BIL',
    icon: Receipt,
    accent: 'bg-amber-600',
    header: 'bg-amber-700',
    chip: 'bg-amber-50 text-amber-800 border-amber-200',
    iconBg: 'bg-amber-500/15 text-amber-700',
  },
  vendor_credit: {
    label: 'Vendor Credit',
    abbrev: 'VC',
    icon: CreditCard,
    accent: 'bg-violet-600',
    header: 'bg-violet-700',
    chip: 'bg-violet-50 text-violet-700 border-violet-200',
    iconBg: 'bg-violet-500/15 text-violet-600',
  },
  credit_note: {
    label: 'Credit Note',
    abbrev: 'CN',
    icon: RotateCcw,
    accent: 'bg-teal-600',
    header: 'bg-teal-700',
    chip: 'bg-teal-50 text-teal-700 border-teal-200',
    iconBg: 'bg-teal-500/15 text-teal-600',
  },
  payment: {
    label: 'Payment',
    abbrev: 'PAY',
    icon: Wallet,
    accent: 'bg-emerald-600',
    header: 'bg-emerald-700',
    chip: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    iconBg: 'bg-emerald-500/15 text-emerald-600',
  },
  bill_payment: {
    label: 'Bill Payment',
    abbrev: 'BP',
    icon: Wallet,
    accent: 'bg-emerald-600',
    header: 'bg-emerald-700',
    chip: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    iconBg: 'bg-emerald-500/15 text-emerald-600',
  },
  job_order: {
    label: 'Job Order',
    abbrev: 'JO',
    icon: Briefcase,
    accent: 'bg-[#0a2547]',
    header: 'bg-[#0a2547]',
    chip: 'bg-slate-100 text-slate-700 border-slate-200',
    iconBg: 'bg-[#0a2547]/10 text-[#0a2547]',
  },
  stock_transfer: {
    label: 'Stock Transfer',
    abbrev: 'ST',
    icon: ArrowLeftRight,
    accent: 'bg-indigo-600',
    header: 'bg-indigo-700',
    chip: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    iconBg: 'bg-indigo-500/15 text-indigo-600',
  },
  stock_adjustment: {
    label: 'Stock Adjustment',
    abbrev: 'SA',
    icon: Package,
    accent: 'bg-slate-600',
    header: 'bg-slate-700',
    chip: 'bg-slate-100 text-slate-700 border-slate-200',
    iconBg: 'bg-slate-500/15 text-slate-600',
  },
  production_order: {
    label: 'Production Order',
    abbrev: 'MO',
    icon: Factory,
    accent: 'bg-purple-600',
    header: 'bg-purple-700',
    chip: 'bg-purple-50 text-purple-700 border-purple-200',
    iconBg: 'bg-purple-500/15 text-purple-600',
  },
};

export function getDocTypeMeta(docType) {
  return (
    DOC_TYPE_META[docType] || {
      label: docType || 'Document',
      abbrev: 'DOC',
      icon: GitBranch,
      accent: 'bg-slate-600',
      header: 'bg-slate-700',
      chip: 'bg-slate-100 text-slate-700 border-slate-200',
      iconBg: 'bg-slate-500/15 text-slate-600',
    }
  );
}
